kind: Deployment
metadata:
  name: pharma-patient-app
  labels:
    app: pharma-patient-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pharma-patient-app
  template:
    metadata:
      labels:
        app: pharma-patient-app
    spec:
      containers:
      - name: pharma-patient-app
        image: sibhanayak/pythonapp
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: pharma-patient-app-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 3003
    targetPort: 3003
    protocol: TCP
  selector:
    app: pharma-patient-app
